In [11]:
import json

import pandas as pd
import yfinance as yf

from datetime import date

from utils.datetime import DATE_FORMAT
from utils.datapath import adj_share_counts_path, daily_prices_path, basket_500_path, basket_all_path
from utils.data import all_securities
from utils.market_data import get_stock_prices

In [2]:
start_date = "2014-01-01"
end_date = date.today().strftime(DATE_FORMAT)
stock_list = [security["code"] for security in all_securities]
black_list = ["2372"]

# prices = get_stock_prices(stock_list, start_date=start_date, end_date=end_date)
# prices_df = pd.DataFrame(prices).reset_index()
# prices_df.to_csv(daily_prices_path)

In [4]:
code = "2372"
ticker = yf.Ticker(f"{code}.T")
ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-30 00:00:00+09:00,4.614366e+09,4.616021e+09,4.614366e+09,4.614366e+09,0,0.0,0.000000e+00
2025-05-01 00:00:00+09:00,4.614366e+09,4.617676e+09,4.614366e+09,4.616021e+09,0,0.0,0.000000e+00
2025-05-02 00:00:00+09:00,4.616021e+09,4.617676e+09,4.614366e+09,4.614366e+09,0,0.0,0.000000e+00
2025-05-07 00:00:00+09:00,4.614366e+09,4.619332e+09,4.614366e+09,4.616021e+09,0,0.0,0.000000e+00
2025-05-08 00:00:00+09:00,4.616021e+09,4.619332e+09,4.616021e+09,4.617676e+09,0,0.0,0.000000e+00
2025-05-09 00:00:00+09:00,4.617676e+09,4.622642e+09,4.617676e+09,4.617676e+09,0,0.0,0.000000e+00
2025-05-12 00:00:00+09:00,NaN,NaN,NaN,NaN,0,0.0,6.041566e-07

In [5]:
shares_df = pd.read_csv(adj_share_counts_path, index_col="Quarter")
prices_df = pd.read_csv(daily_prices_path)

shares_df = shares_df.drop(["2025 Q2"], axis=0)
prices_df = prices_df.drop(columns=["Unnamed: 0"] + black_list)

# shares_df

In [6]:
prices_df["Quarter"] = prices_df["Date"].apply(lambda date: f"{pd.Timestamp(date).year} Q{pd.Timestamp(date).quarter}")
quarterly_prices_df = prices_df.ffill().drop_duplicates(subset="Quarter", keep="last").drop(columns="Date").set_index("Quarter")
quarterly_prices_df = quarterly_prices_df.drop(["2025 Q2"], axis=0)

In [7]:
quarterly_prices_df

,6178,8316,8411,8306,9501,9432,8421,6758,4612,7203,...,4894,9330,5889,151A,135A,143A,9345,3045,5591,3350
Quarter,,,,,,,,,,,,,,,,,,,,,
2014 Q1,NaN,1118.873291,1312.161255,390.499817,416.000000,39.968506,143719.937500,386.126160,279.278168,849.510925,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420.471039,NaN,330.000000
2014 Q2,NaN,1077.001221,1337.889893,427.690308,422.000000,44.940552,149962.015625,329.342896,382.846802,887.130737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,454.613373,NaN,340.000000
2014 Q3,NaN,1149.833252,1282.166870,433.233612,384.000000,49.162498,158411.656250,389.846466,441.979553,953.309814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,460.629761,NaN,580.000000
2014 Q4,NaN,1125.144287,1325.364136,464.178955,492.000000,44.765911,164273.109375,484.126221,631.143188,1114.825439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,464.789795,NaN,510.000000
2015 Q1,NaN,1183.394531,1406.909668,525.686890,455.000000,53.957401,182454.578125,624.615906,791.074280,1254.741943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,506.496735,NaN,470.000000
2015 Q2,NaN,1403.922974,1766.134644,621.889526,667.000000,64.680321,171165.609375,677.776733,621.173035,1227.800171,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,569.761108,NaN,470.000000
2015 Q3,NaN,1179.113159,1509.621948,512.526184,797.000000,61.662884,168114.515625,569.372131,376.756104,1058.104248,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,505.088409,NaN,400.000000
2015 Q4,1271.122437,1203.678223,1649.138550,541.643677,699.000000,71.374306,172004.640625,589.703247,535.533325,1136.577881,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,495.770905,NaN,300.000000
2016 Q1,1040.606201,891.652222,1163.426147,379.437256,619.000000,72.407448,175273.468750,568.291626,455.575684,919.690613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,503.880615,NaN,310.000000
2016 Q2,859.782043,764.646606,1026.389404,331.707520,432.000000,71.690536,176843.343750,586.953125,456.487885,780.624512,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,526.354126,NaN,270.000000
2016 Q3,891.760925,902.337036,1191.969971,373.899963,435.000000,69.784836,180767.953125,646.866333,614.697388,908.057983,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.210236,NaN,380.000000
2016 Q4,1030.149902,1190.657715,1483.246338,533.127625,472.000000,74.291977,182416.312500,643.330505,588.108582,1080.744385,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,504.594482,NaN,330.000000
2017 Q1,1003.691101,1079.867798,1468.350342,524.565552,436.000000,72.748528,189199.875000,741.838867,715.516479,966.480896,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,554.942383,NaN,280.000000
2017 Q2,1001.535400,1169.033813,1478.427002,565.874084,463.000000,81.290955,187667.546875,844.270020,788.479248,942.646851,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,638.547363,NaN,290.000000
2017 Q3,972.676147,1153.282837,1445.835449,554.743469,454.000000,80.091316,187506.234375,824.571716,709.631348,1089.318481,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,631.760925,NaN,270.000000
2017 Q4,945.596558,1299.578735,1500.852051,627.398438,446.000000,82.327713,188715.984375,1001.265747,665.438965,1170.977051,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,660.737000,NaN,310.000000
2018 Q1,942.555542,1214.177612,1431.552856,536.714844,410.000000,77.277962,193781.140625,1016.590210,728.903076,1127.624634,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,807.249939,NaN,300.000000
2018 Q2,892.521301,1172.778809,1394.903687,485.969452,516.000000,79.422829,197345.125000,1118.920898,894.641907,1184.625244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,894.586426,NaN,230.000000
2018 Q3,1013.329102,1272.014771,1510.145386,554.412781,558.000000,82.259605,198339.718750,1376.130493,795.237183,1188.927734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,734.992615,NaN,200.000000
2018 Q4,948.122192,1011.010376,1297.567017,420.559387,653.000000,71.840897,198919.906250,1052.148926,709.738525,1073.470215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,654.796509,NaN,140.000000
2019 Q1,990.094299,1075.082520,1333.901123,438.635834,700.000000,76.884918,203611.421875,917.617798,821.107117,1106.751099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,721.565552,NaN,140.000000
2019 Q2,932.033264,1055.666626,1215.539795,408.330109,562.000000,82.018211,202759.843750,1115.760132,793.187500,1141.043823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,850.776245,NaN,125.000000
2019 Q3,778.975952,1049.561401,1318.497803,447.217407,529.000000,85.803726,202844.984375,1253.847290,1064.541138,1247.931152,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,767.639099,NaN,121.000000
2019 Q4,803.245605,1146.990479,1339.995117,483.751465,467.000000,91.761398,207869.296875,1462.064331,1074.679321,1334.054932,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,844.148132,NaN,113.000000
2020 Q1,681.223877,745.060852,1012.085205,338.034302,377.000000,87.255585,198877.000000,1268.465820,1078.490234,1143.806763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,747.179016,NaN,48.000000
2020 Q2,617.588135,861.236938,1082.505371,353.635864,331.000000,85.222839,198789.453125,1458.706177,1498.052490,1189.727661,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,834.981140,NaN,74.000000
2020 Q3,576.587402,854.825317,1102.580078,359.098206,289.000000,74.461578,201766.921875,1586.718384,2065.554932,1220.488281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,846.274414,NaN,69.000000
2020 Q4,646.667236,934.081543,1100.056030,393.618561,272.000000,91.622375,207897.000000,2031.797485,2169.179199,1400.955688,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,909.025940,NaN,55.000000
2021 Q1,833.800476,1201.418457,1376.191650,521.175659,369.000000,100.098923,213982.921875,2296.509033,1526.849365,1541.567993,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1008.837769,NaN,60.000000
2021 Q2,769.239380,1148.348511,1366.293945,528.574463,330.000000,101.948051,215782.593750,2142.021973,1447.223633,1737.305786,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1205.490723,NaN,61.000000
2021 Q3,798.224304,1212.961914,1397.197754,591.071594,320.000000,110.553085,216412.468750,2466.840820,1167.951782,1810.108276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1100.783325,NaN,57.000000
2021 Q4,757.831421,1212.654419,1290.060181,561.423706,297.000000,112.882408,219291.984375,2866.922607,1208.352661,1905.591431,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1087.337280,NaN,40.000000
2022 Q1,800.269226,1201.582764,1416.085327,695.746948,403.000000,129.149521,227234.609375,2521.307373,1042.613647,2036.704712,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1137.576538,NaN,62.000000
2022 Q2,863.246765,1240.026001,1394.396729,667.470520,567.000000,141.936951,225016.781250,2197.478760,978.881836,1924.445923,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1298.915649,NaN,56.000000
2022 Q3,853.092041,1272.663086,1450.352051,610.481567,462.000000,144.555862,239432.625000,1845.945068,947.898438,1741.458008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1161.041138,NaN,55.000000
2022 Q4,988.311218,1674.956177,1722.786133,833.028625,476.000000,139.226593,255327.062500,1994.837402,1011.784973,1682.511963,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1211.521240,NaN,47.000000
2023 Q1,1004.126343,1675.588623,1782.995850,809.869263,473.000000,148.834930,259238.921875,2390.793457,1205.572510,1778.787476,...,NaN,NaN,NaN,NaN,NaN,NaN,4742.383301,1289.956055,NaN,31.000000
2023 Q2,966.815552,1947.895508,2087.757080,1017.231567,527.099976,160.123398,258197.796875,2586.285889,1157.870850,2184.218506,...,1578.0,NaN,NaN,NaN,NaN,NaN,2717.523438,1317.897339,NaN,22.000000
2023 Q3,1139.675903,2365.536621,2458.795898,1230.821045,668.799988,168.146744,261983.703125,2441.661377,984.630615,2561.314941,...,1736.0,1450.0,NaN,NaN,NaN,NaN,1815.289917,1286.821167,2302.0,19.000000
2023 Q4,1198.682251,2215.175049,2334.452881,1175.514038,738.500000,164.052567,255074.437500,2675.055420,1123.680054,2478.090088,...,2321.0,1123.0,1214.201660,NaN,NaN,NaN,1315.470215,1223.426270,2553.0,17.000000
2024 Q1,1477.144165,2863.629150,2987.361328,1523.844116,942.000000,173.743835,260072.734375,2587.283203,1059.117798,3677.095215,...,3700.0,963.0,2169.721191,1060.000000,6160.0,1921.0,1253.484741,1303.991699,2715.0,20.000000
2024 Q2,1542.923950,3453.162109,3308.561768,1699.823486,866.200012,146.605438,252024.250000,2720.936279,1039.864136,3184.428223,...,7810.0,946.0,2960.517090,1170.000000,3800.0,1124.0,1345.971069,1257.832642,1785.0,99.000000
2024 Q3,1344.913208,3000.088379,2892.774658,1453.500000,636.900024,144.255478,236024.250000,2770.308105,1088.979858,2497.555664,...,9360.0,796.0,2912.000000,897.666687,2630.0,1130.0,1602.768188,1229.832886,1044.0,99.099998
2024 Q4,1467.491333,3708.483643,3815.979736,1846.000000,475.000000,155.261337,213236.375000,3360.276611,1023.500000,3090.387451,...,4610.0,725.0,2410.000000,908.000000,2003.0,942.0,1860.000000,1336.902954,911.0,348.000000
2025 Q1,1493.000000,3795.000000,4051.000000,2011.000000,429.700012,144.699997,210900.000000,3765.000000,1121.000000,2616.000000,...,8310.0,861.0,2270.000000,962.000000,1930.0,916.0,2045.000000,1349.000000,1111.0,401.000000

In [8]:
# quarterly_prices_df

In [9]:
market_cap_df = quarterly_prices_df.mul(shares_df)

In [10]:
jp_all = market_cap_df.apply(
    lambda x: x.sort_values(ascending=False).index.tolist(),
    axis=1
).to_frame(name='jp_all')

jp_500 = market_cap_df.apply(
    lambda x: x.sort_values(ascending=False).head(500).index.tolist(),
    axis=1
).to_frame(name='jp_500')

In [13]:
with open(basket_all_path, 'w', encoding='utf-8') as f:
    json.dump(jp_all["jp_all"].to_dict(), f)

with open(basket_500_path, 'w', encoding='utf-8') as f:
    json.dump(jp_500["jp_500"].to_dict(), f)

In [60]:
# TODO:
# 1. Convert dates in prices_df to quarters
# 2. For each quarter, for each stock, multiply quarterly price with shares to get market cap
# 3. For each quarter, get 500 stocks with highest market cap
# 4. Voila, you have your constituents

In [1]:
from utils.data import jp_500, jp_all

In [4]:
# jp_all

In [ ]:
# jp_500

{'2014 Q1': ['9031',
  '4651',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904',
  '2907'],
 '2014 Q2': ['9031',
  '2354',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904',
  '2907',
  '2908'],
 '2014 Q3': ['9031',
  '3760',
  '3691',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904'],
 '2014 Q4': ['9031',
  '4958',
  '2489',
  '9973',
  '2170',
  '3760',
  '3691',
  '8095',
  '4769',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',