In [2]:
import json

import pandas as pd
import yfinance as yf

from datetime import date

from utils.datetime import DATE_FORMAT, date_string_to_quarter, get_today, get_current_quarter
from utils.datapath import adj_share_counts_path, daily_prices_path, basket_500_path, basket_all_path
from utils.data import all_securities
from utils.market_data import get_stock_prices

In [17]:
start_date = "2014-01-01"
end_date = get_today()
stock_list = [security["code"] for security in all_securities]
black_list = ["2372"]

# prices = get_stock_prices(stock_list, start_date=start_date, end_date=end_date)
# prices_df = pd.DataFrame(prices).reset_index()
# prices_df.to_csv(daily_prices_path)

In [18]:
code = "2372"
ticker = yf.Ticker(f"{code}.T")
ticker.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-04-30 00:00:00+09:00,4.614366e+09,4.616021e+09,4.614366e+09,4.614366e+09,0,0.0,0.000000e+00
2025-05-01 00:00:00+09:00,4.614366e+09,4.617676e+09,4.614366e+09,4.616021e+09,0,0.0,0.000000e+00
2025-05-02 00:00:00+09:00,4.616021e+09,4.617676e+09,4.614366e+09,4.614366e+09,0,0.0,0.000000e+00
2025-05-07 00:00:00+09:00,4.614366e+09,4.619332e+09,4.614366e+09,4.616021e+09,0,0.0,0.000000e+00
2025-05-08 00:00:00+09:00,4.616021e+09,4.619332e+09,4.616021e+09,4.617676e+09,0,0.0,0.000000e+00
2025-05-09 00:00:00+09:00,4.617676e+09,4.622642e+09,4.617676e+09,4.617676e+09,0,0.0,0.000000e+00
2025-05-12 00:00:00+09:00,NaN,NaN,NaN,NaN,0,0.0,6.041566e-07

In [19]:
shares_df = pd.read_csv(adj_share_counts_path, index_col="Quarter")
prices_df = pd.read_csv(daily_prices_path)

# shares_df = shares_df.drop([get_current_quarter()], axis=0)
prices_df = prices_df.drop(columns=["Unnamed: 0"] + black_list)

# shares_df

In [20]:
prices_df["Quarter"] = prices_df["Date"].apply(date_string_to_quarter)
quarterly_prices_df = prices_df.ffill().drop_duplicates(subset="Quarter", keep="last").drop(columns="Date").set_index("Quarter")
quarterly_prices_df = quarterly_prices_df.drop([get_current_quarter()], axis=0)

In [21]:
prices_df

,Date,6178,8316,8411,8306,9501,9432,8421,6758,4612,...,9330,5889,151A,135A,143A,9345,3045,5591,3350,Quarter
0,2014-01-06,NaN,1377.972534,1441.248047,464.625793,516.000000,38.969852,140142.765625,350.482147,316.761475,...,NaN,NaN,NaN,NaN,NaN,NaN,407.423004,NaN,440.0,2014-Q1
1,2014-01-07,NaN,1362.746582,1428.605225,458.530121,511.000000,38.690006,140142.765625,350.093170,313.041077,...,NaN,NaN,NaN,NaN,NaN,NaN,411.835632,NaN,440.0,2014-Q1
2,2014-01-08,NaN,1380.510376,1479.175781,468.689606,516.000000,39.809425,140437.015625,354.955566,313.041077,...,NaN,NaN,NaN,NaN,NaN,NaN,411.835632,NaN,440.0,2014-Q1
3,2014-01-09,NaN,1357.671021,1466.533325,461.239380,512.000000,39.319679,139774.906250,368.375763,314.635529,...,NaN,NaN,NaN,NaN,NaN,NaN,411.835632,NaN,430.0,2014-Q1
4,2014-01-10,NaN,1365.284302,1498.139648,464.625793,509.000000,39.599533,139848.484375,356.900482,318.001617,...,NaN,NaN,NaN,NaN,NaN,NaN,399.701233,NaN,440.0,2014-Q1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2802,2025-05-23,1333.0,3617.000000,3894.000000,1942.500000,394.500000,150.800003,204000.000000,3683.000000,1057.500000,...,781.0,2221.0,908.0,2226.0,837.0,2220.0,1375.000000,1634.0,816.0,2025-Q2
2803,2025-05-26,1331.5,3603.000000,3907.000000,1955.000000,396.500000,152.100006,204400.000000,3740.000000,1067.500000,...,787.0,2208.0,920.0,2382.0,824.0,2220.0,1400.000000,1817.0,966.0,2025-Q2
2804,2025-05-27,1334.0,3621.000000,3959.000000,1977.000000,405.399994,151.399994,203500.000000,3809.000000,1064.000000,...,780.0,2242.0,926.0,2480.0,821.0,2148.0,1400.000000,1776.0,1116.0,2025-Q2
2805,2025-05-28,1341.5,3626.000000,3981.000000,1963.000000,399.600006,155.000000,201400.000000,3821.000000,1068.000000,...,780.0,2287.0,916.0,2420.0,839.0,2150.0,1377.000000,1720.0,1222.0,2025-Q2
2806,2025-05-29,1381.0,3682.000000,4007.000000,2005.000000,392.500000,155.899994,202900.000000,3970.000000,1073.500000,...,780.0,2320.0,908.0,2525.0,841.0,2179.0,1390.000000,1761.0,1140.0,2025-Q2

In [24]:
# quarterly_prices_df

In [25]:
market_cap_df = quarterly_prices_df.mul(shares_df)

In [26]:
market_cap_df

,1301,1332,135A,1375,1376,1377,1379,137A,1381,1382,...,9984,9986,9987,9989,9990,9991,9993,9994,9996,9997
Quarter,,,,,,,,,,,,,,,,,,,,,
2014-Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-Q2,2.770082e+10,9.134517e+10,NaN,NaN,1.122597e+10,9.134917e+10,6.082230e+10,NaN,1.103700e+10,8.873640e+08,...,4.899923e+12,5.320891e+09,2.546707e+11,3.502352e+11,4.857145e+10,3.143107e+10,1.557620e+10,1.846075e+10,7.058927e+09,5.140207e+10
2015-Q3,2.564540e+10,9.341566e+10,NaN,NaN,9.232649e+09,7.696865e+10,5.253050e+10,NaN,9.807970e+09,7.766154e+08,...,3.734752e+12,5.089494e+09,2.599672e+11,3.035884e+11,4.483663e+10,2.585245e+10,1.469194e+10,2.224880e+10,7.241541e+09,5.083057e+10
2015-Q4,2.711368e+10,1.781714e+11,NaN,NaN,1.121362e+10,1.123522e+11,5.678590e+10,NaN,1.164425e+10,7.559790e+08,...,4.187847e+12,5.126644e+09,3.024756e+11,3.780352e+11,3.899300e+10,2.607863e+10,1.530517e+10,1.980683e+10,8.223770e+09,5.215382e+10
2016-Q1,2.573041e+10,1.442972e+11,NaN,NaN,9.426725e+09,1.121554e+11,5.549552e+10,NaN,1.194307e+10,6.878790e+08,...,3.675870e+12,4.994383e+09,2.510994e+11,4.091664e+11,3.483496e+10,2.627528e+10,1.533788e+10,1.803961e+10,7.393593e+09,4.492665e+10
2016-Q2,2.592990e+10,1.382285e+11,NaN,NaN,1.198650e+10,8.740687e+10,4.692199e+10,NaN,8.851828e+09,6.232184e+08,...,3.965872e+12,4.877179e+09,2.107234e+11,4.645636e+11,2.236652e+10,2.553135e+10,1.562050e+10,1.495841e+10,7.187756e+09,4.508384e+10
2016-Q3,2.736591e+10,1.148503e+11,NaN,NaN,1.377359e+10,1.005732e+11,4.552073e+10,NaN,8.197754e+09,7.401578e+08,...,4.485082e+12,5.099631e+09,2.196291e+11,4.126676e+11,2.424341e+10,2.278992e+10,1.552145e+10,1.376341e+10,7.331148e+09,4.950354e+10
2016-Q4,2.722605e+10,1.490293e+11,NaN,NaN,1.438132e+10,1.307543e+11,5.288112e+10,NaN,9.249090e+09,7.855454e+08,...,5.338002e+12,5.442948e+09,2.527571e+11,3.950692e+11,2.647780e+10,2.884469e+10,1.620270e+10,1.575596e+10,7.762352e+09,5.721113e+10
2017-Q1,2.937459e+10,1.481266e+11,NaN,NaN,1.386935e+10,1.378752e+11,5.154723e+10,NaN,1.143899e+10,7.015933e+08,...,5.421905e+12,5.736678e+09,2.431672e+11,3.674139e+11,2.888520e+10,2.862950e+10,1.680196e+10,1.556223e+10,8.353200e+09,6.667748e+10
2017-Q2,3.091480e+10,1.753834e+11,NaN,NaN,1.392350e+10,1.388546e+11,5.073019e+10,NaN,1.665292e+10,6.830271e+08,...,6.273388e+12,5.717032e+09,2.485798e+11,4.119897e+11,2.879348e+10,3.546945e+10,1.662702e+10,1.474171e+10,8.515117e+09,1.074200e+11
2017-Q3,3.341782e+10,1.690022e+11,NaN,NaN,1.488084e+10,1.271318e+11,5.058676e+10,NaN,1.820022e+10,6.877752e+08,...,6.280124e+12,6.319625e+09,2.683531e+11,4.608098e+11,3.329176e+10,3.237653e+10,1.631340e+10,1.577046e+10,9.601335e+09,9.544490e+10
2017-Q4,4.298145e+10,1.582542e+11,NaN,NaN,1.640099e+10,1.557661e+11,5.294024e+10,NaN,1.945286e+10,6.568158e+08,...,6.166875e+12,7.766606e+09,3.110265e+11,5.179694e+11,3.183039e+10,3.720362e+10,1.641676e+10,3.237136e+10,1.032782e+10,1.117011e+11
2018-Q1,3.859821e+10,1.494031e+11,NaN,NaN,1.516736e+10,1.499886e+11,5.358406e+10,NaN,2.298965e+10,6.705676e+08,...,5.511007e+12,7.039575e+09,2.956311e+11,4.890713e+11,2.667537e+10,2.998279e+10,1.665066e+10,3.040807e+10,1.095073e+10,1.019921e+11
2018-Q2,3.651287e+10,1.477791e+11,NaN,NaN,1.639403e+10,1.677275e+11,5.231567e+10,NaN,2.100011e+10,6.602503e+08,...,5.527120e+12,6.668623e+09,3.155806e+11,4.469767e+11,2.321521e+10,2.889818e+10,1.763599e+10,3.154798e+10,1.154017e+10,1.129916e+11
2018-Q3,3.451975e+10,2.014353e+11,NaN,NaN,1.507089e+10,1.637201e+11,5.163224e+10,NaN,1.537498e+10,6.375483e+08,...,7.968069e+12,6.388007e+09,3.645480e+11,4.069440e+11,2.211638e+10,3.323742e+10,1.644367e+10,2.909338e+10,1.319552e+10,1.091836e+11
2018-Q4,2.924719e+10,1.670906e+11,NaN,NaN,1.326559e+10,1.354334e+11,5.123698e+10,NaN,1.159996e+10,5.570811e+08,...,5.075569e+12,5.373904e+09,3.781988e+11,3.286725e+11,2.609075e+10,2.792917e+10,1.662518e+10,2.103520e+10,1.204272e+10,8.144201e+10
2019-Q1,2.947244e+10,2.310508e+11,NaN,NaN,1.376510e+10,1.512589e+11,5.231426e+10,NaN,1.148994e+10,5.811525e+08,...,7.480950e+12,5.616072e+09,4.358578e+11,3.093019e+11,2.755263e+10,2.866506e+10,1.617419e+10,2.154404e+10,1.211997e+10,7.038997e+10
2019-Q2,2.977851e+10,1.825763e+11,NaN,NaN,1.290601e+10,1.270475e+11,4.957277e+10,NaN,1.230201e+10,5.660219e+08,...,7.193350e+12,5.667086e+09,4.298356e+11,2.957283e+11,2.351276e+10,2.633846e+10,1.574163e+10,2.056814e+10,1.178351e+10,6.029787e+10
2019-Q3,2.886412e+10,1.680488e+11,NaN,NaN,1.277671e+10,1.490881e+11,5.441903e+10,NaN,1.139610e+10,6.843156e+08,...,5.934844e+12,6.032157e+09,3.966412e+11,3.482100e+11,2.134921e+10,2.410828e+10,1.620031e+10,2.138297e+10,1.166179e+10,5.692051e+10
2019-Q4,2.987195e+10,1.793251e+11,NaN,NaN,1.461556e+10,1.487096e+11,5.426286e+10,NaN,1.182652e+10,1.154052e+09,...,6.657675e+12,6.488150e+09,3.054968e+11,4.050501e+11,2.201736e+10,3.123369e+10,1.662964e+10,2.262237e+10,1.231910e+10,5.905804e+10
2020-Q1,2.712634e+10,1.326269e+11,NaN,NaN,1.334327e+10,1.330878e+11,5.309032e+10,NaN,1.046519e+10,4.339730e+08,...,5.330709e+12,6.045036e+09,2.715041e+11,3.578259e+11,1.537173e+10,2.261117e+10,1.543948e+10,1.984860e+10,1.032346e+10,4.050208e+10
2020-Q2,2.899307e+10,1.298512e+11,NaN,NaN,1.447945e+10,1.402811e+11,5.717766e+10,NaN,1.420305e+10,6.155402e+08,...,7.668668e+12,6.364598e+09,2.772749e+11,3.692017e+11,1.509310e+10,2.670622e+10,1.695008e+10,2.244168e+10,1.211358e+10,5.105298e+10
2020-Q3,2.981672e+10,1.251099e+11,NaN,7.636254e+10,1.640483e+10,1.537377e+11,6.343461e+10,NaN,1.766356e+10,6.224177e+08,...,9.133020e+12,6.655718e+09,2.786078e+11,4.135352e+11,1.446631e+10,2.751463e+10,1.792416e+10,2.110029e+10,1.134655e+10,8.086866e+10
2020-Q4,3.145487e+10,1.192321e+11,NaN,6.245497e+10,1.604349e+10,1.464076e+11,5.901249e+10,NaN,1.779249e+10,6.499279e+08,...,1.137197e+13,6.100415e+09,2.594947e+11,4.297011e+11,1.356373e+10,2.812993e+10,1.723361e+10,2.167804e+10,1.117321e+10,9.633290e+10
2021-Q1,3.329339e+10,1.501326e+11,NaN,7.383619e+10,1.657312e+10,1.674980e+11,6.039334e+10,NaN,1.807614e+10,6.320463e+08,...,1.319962e+13,6.525781e+09,3.032955e+11,4.259288e+11,1.551942e+10,2.878783e+10,1.731870e+10,2.468447e+10,1.144322e+10,1.109433e+11
2021-Q2,3.156129e+10,1.492831e+11,NaN,6.323055e+10,1.525419e+10,1.502232e+11,5.555435e+10,NaN,1.760937e+10,6.533598e+08,...,1.100348e+13,6.803772e+09,2.283341e+11,3.712425e+11,1.598112e+10,2.624657e+10,1.711969e+10,2.287363e+10,1.163338e+10,8.351168e+10
2021-Q3,3.292450e+10,1.854268e+11,NaN,5.910233e+10,1.596446e+10,1.444681e+11,5.721040e+10,NaN,1.708056e+10,6.395729e+08,...,9.198402e+12,8.193526e+09,2.327991e+11,3.622498e+11,1.464722e+10,2.680361e+10,1.738592e+10,2.521690e+10,1.152807e+10,7.383417e+10
2021-Q4,3.357875e+10,1.546753e+11,NaN,4.516702e+10,1.561592e+10,1.359529e+11,5.551902e+10,NaN,1.713338e+10,6.402607e+08,...,7.712570e+12,9.295334e+09,2.356441e+11,3.192366e+11,1.328766e+10,2.507138e+10,1.629422e+10,2.485125e+10,1.143584e+10,6.130000e+10
2022-Q1,3.726818e+10,1.583032e+11,NaN,4.367638e+10,1.657345e+10,1.535707e+11,5.691808e+10,NaN,1.739773e+10,6.251310e+08,...,7.920706e+12,9.222662e+09,2.600896e+11,3.196968e+11,1.318351e+10,2.500090e+10,1.653897e+10,2.554790e+10,1.031161e+10,6.359851e+10
2022-Q2,3.867819e+10,1.655410e+11,NaN,3.445569e+10,1.666975e+10,1.904961e+11,5.772112e+10,NaN,1.748828e+10,9.514231e+08,...,7.462406e+12,8.720881e+09,2.747856e+11,3.256231e+11,1.593117e+10,2.574806e+10,1.515545e+10,2.588638e+10,9.724689e+09,6.526619e+10
2022-Q3,4.051277e+10,1.598192e+11,NaN,3.875223e+10,1.534479e+10,2.002326e+11,5.687433e+10,NaN,1.592697e+10,1.504728e+09,...,7.014066e+12,8.624706e+09,2.394827e+11,3.833653e+11,1.875807e+10,2.494334e+10,1.258337e+10,2.565433e+10,9.017608e+09,6.204995e+10
2022-Q4,4.254424e+10,1.609921e+11,NaN,3.914053e+10,1.512337e+10,1.829023e+11,5.640938e+10,NaN,1.571482e+10,1.252369e+09,...,8.076282e+12,8.447446e+09,2.585651e+11,4.269915e+11,2.042250e+10,2.656176e+10,1.311555e+10,2.590309e+10,8.883953e+09,6.045067e+10
2023-Q1,3.844395e+10,1.621541e+11,NaN,3.913486e+10,1.753914e+10,1.634622e+11,5.663767e+10,NaN,1.609559e+10,1.323373e+09,...,7.449342e+12,1.129591e+10,2.447918e+11,4.018691e+11,2.249051e+10,2.867369e+10,1.339727e+10,2.728530e+10,9.568039e+09,6.331790e+10
2023-Q2,4.058054e+10,1.929411e+11,NaN,3.808071e+10,1.559179e+10,1.756421e+11,5.595232e+10,NaN,1.651666e+10,1.351789e+09,...,9.732283e+12,1.219151e+10,2.862276e+11,4.718505e+11,2.779348e+10,2.837899e+10,1.307711e+10,2.845731e+10,9.528198e+09,6.413097e+10
2023-Q3,4.420726e+10,2.214478e+11,NaN,3.515539e+10,1.562028e+10,1.832300e+11,5.583399e+10,NaN,1.624450e+10,1.801068e+09,...,9.130979e+12,1.297909e+10,3.412411e+11,4.544958e+11,2.439404e+10,3.243991e+10,1.309435e+10,3.070463e+10,1.233531e+10,6.150736e+10
2023-Q4,4.230698e+10,2.296982e+11,NaN,3.656496e+10,1.510447e+10,1.661257e+11,5.327416e+10,NaN,1.565676e+10,1.684077e+09,...,9.073805e+12,1.243679e+10,3.445847e+11,5.079855e+11,2.189206e+10,3.498348e+10,1.303355e+10,3.214009e+10,1.331148e+10,5.693233e+10
2024-Q1,4.309489e+10,2.979540e+11,6.229353e+10,4.147038e+10,1.547788e+10,1.586939e+11,5.733365e+10,5.716023e+09,1.692476e+10,1.602109e+09,...,1.292737e+13,1.324871e+10,3.427667e+11,5.314835e+11,2.468669e+10,3.895012e+10,1.312068e+10,3.449007e+10,1.548670e+10,5.778006e+10
2024-Q2,4.705616e+10,2.647684e+11,3.841800e+10,4.001494e+10,1.574019e+10,1.479276e+11,5.844733e+10,4.685653e+09,1.673484e+10,1.715308e+09,...,1.501586e+13,1.337683e+10,3.636714e+11,4.599357e+11,2.288710e+10,3.429981e+10,1.378733e+10,3.369163e+10,1.532356e+10,7.145999e+10
2024-Q3,5.028141e+10,2.851849e+11,2.658930e+10,3.962132e+10,1.524472e+10,1.515561e+11,5.632661e+10,3.423518e+09,1.578578e+10,1.365696e+09,...,1.221131e+13,1.330014e+10,3.758417e+11,4.877304e+11,2.342132e+10,2.995785e+10,1.288044e+10,3.222175e+10,1.412435e+10,6.864150e+10
2024-Q4,4.745914e+10,2.795578e+11,2.025033e+10,4.278953e+10,1.555150e+10,1.500995e+11,5.571734e+10,2.860228e+09,1.484234e+10,1.368743e+09,...,1.330586e+13,1.293640e+10,3.559977e+11,4.635521e+11,2.749826e+10,3.436542e+10,1.270104e+10,3.093285e+10,1.543689e+10,7.384338e+10
2025-Q1,4.929144e+10,2.805827e+11,1.951230e+10,4.491805e+10,1.548633e+10,1.459074e+11,5.875287e+10,3.406412e+09,1.642036e+10,1.379624e+09,...,1.083425e+13,1.300878e+10,3.696321e+11,4.922960e+11,2.475583e+10,3.491713e+10,1.259131e+10,3.090902e+10,1.711429e+10,9.111359e+10

In [31]:
jp_all = market_cap_df.apply(
    lambda x: x.sort_values(ascending=False).index.tolist(),
    axis=1
).to_frame(name='jp_all')

jp_500 = market_cap_df.apply(
    lambda x: x.sort_values(ascending=False).head(500).index.tolist(),
    axis=1
).to_frame(name='jp_500')

In [34]:
with open(basket_all_path, 'w', encoding='utf-8') as f:
    json.dump(jp_all["jp_all"].to_dict(), f)

with open(basket_500_path, 'w', encoding='utf-8') as f:
    json.dump(jp_500["jp_500"].to_dict(), f)

In [ ]:
# TODO:
# 1. Convert dates in prices_df to quarters - DONE
# 2. For each quarter, for each stock, multiply quarterly price with shares to get market cap - DONE
# 3. For each quarter, get 500 stocks with highest market cap - DONE
# 4. Voila, you have your constituents - DONE

In [29]:
from utils.data import jp_500, jp_all

In [4]:
# jp_all

In [30]:
jp_500

{'2014 Q1': ['9031',
  '4651',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904',
  '2907'],
 '2014 Q2': ['9031',
  '2354',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904',
  '2907',
  '2908'],
 '2014 Q3': ['9031',
  '3760',
  '3691',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2170',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2489',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',
  '2884',
  '2892',
  '2894',
  '2897',
  '2899',
  '2901',
  '2902',
  '2903',
  '2904'],
 '2014 Q4': ['9031',
  '4958',
  '2489',
  '9973',
  '2170',
  '3760',
  '3691',
  '8095',
  '4769',
  '1301',
  '1332',
  '135A',
  '1375',
  '1376',
  '1377',
  '1379',
  '137A',
  '1381',
  '1382',
  '1383',
  '1384',
  '138A',
  '1401',
  '1407',
  '1414',
  '1417',
  '1419',
  '141A',
  '1420',
  '1429',
  '142A',
  '1430',
  '1431',
  '1433',
  '1434',
  '1435',
  '143A',
  '1443',
  '1444',
  '1446',
  '1447',
  '1449',
  '1451',
  '148A',
  '1491',
  '149A',
  '1514',
  '1515',
  '1518',
  '151A',
  '153A',
  '156A',
  '1605',
  '165A',
  '1662',
  '1663',
  '166A',
  '167A',
  '168A',
  '1711',
  '1712',
  '1716',
  '1717',
  '1718',
  '1719',
  '1720',
  '1721',
  '1723',
  '1724',
  '1726',
  '1730',
  '1736',
  '1738',
  '1743',
  '1757',
  '1758',
  '1762',
  '1764',
  '1766',
  '1768',
  '176A',
  '1770',
  '1771',
  '1775',
  '1776',
  '1777',
  '177A',
  '1780',
  '1783',
  '1786',
  '1787',
  '1788',
  '1789',
  '1793',
  '1795',
  '1798',
  '1799',
  '1801',
  '1802',
  '1803',
  '1805',
  '1807',
  '1808',
  '1810',
  '1811',
  '1812',
  '1813',
  '1814',
  '1815',
  '1820',
  '1821',
  '1822',
  '1826',
  '1827',
  '1828',
  '1832',
  '1833',
  '1835',
  '1840',
  '1841',
  '1844',
  '1847',
  '1848',
  '1850',
  '1852',
  '1853',
  '1860',
  '1861',
  '1866',
  '1867',
  '1869',
  '1870',
  '1871',
  '1873',
  '1878',
  '1879',
  '187A',
  '1882',
  '1884',
  '1885',
  '1887',
  '1888',
  '1890',
  '1893',
  '1897',
  '1898',
  '1899',
  '1904',
  '1905',
  '1909',
  '190A',
  '1911',
  '1914',
  '1921',
  '1925',
  '1926',
  '1928',
  '1929',
  '1930',
  '1934',
  '1938',
  '1939',
  '1941',
  '1942',
  '1944',
  '1945',
  '1946',
  '1948',
  '1949',
  '194A',
  '1950',
  '1951',
  '1952',
  '1959',
  '1960',
  '1961',
  '1963',
  '1964',
  '1965',
  '1966',
  '1967',
  '1968',
  '1969',
  '196A',
  '1972',
  '1973',
  '1975',
  '1976',
  '1979',
  '197A',
  '1980',
  '1981',
  '1982',
  '198A',
  '1992',
  '1994',
  '1997',
  '1999',
  '2001',
  '2002',
  '2003',
  '2004',
  '202A',
  '2055',
  '2058',
  '205A',
  '2060',
  '208A',
  '2107',
  '2108',
  '2109',
  '2112',
  '2114',
  '2117',
  '211A',
  '2120',
  '2121',
  '2122',
  '2124',
  '2127',
  '212A',
  '2130',
  '2134',
  '2136',
  '2137',
  '2138',
  '2139',
  '2146',
  '2148',
  '2150',
  '2152',
  '2153',
  '2154',
  '2156',
  '2157',
  '2158',
  '2160',
  '2162',
  '2163',
  '2164',
  '2168',
  '2169',
  '2172',
  '2173',
  '2175',
  '2179',
  '2180',
  '2181',
  '2183',
  '2185',
  '2186',
  '2193',
  '2195',
  '2196',
  '2198',
  '2201',
  '2204',
  '2206',
  '2207',
  '2208',
  '2209',
  '220A',
  '2211',
  '2212',
  '2215',
  '2216',
  '2217',
  '2218',
  '2220',
  '2221',
  '2222',
  '2224',
  '2226',
  '2264',
  '2266',
  '2267',
  '2268',
  '2269',
  '2270',
  '2281',
  '2282',
  '2286',
  '2288',
  '2291',
  '2292',
  '2293',
  '2294',
  '2296',
  '2300',
  '2301',
  '2303',
  '2304',
  '2305',
  '2307',
  '2311',
  '2315',
  '2317',
  '2321',
  '2323',
  '2325',
  '2326',
  '2327',
  '2329',
  '2330',
  '2331',
  '2332',
  '2334',
  '2335',
  '2337',
  '2338',
  '2340',
  '2341',
  '2342',
  '2344',
  '2345',
  '2349',
  '2351',
  '2353',
  '2354',
  '2359',
  '2370',
  '2371',
  '2372',
  '2373',
  '2374',
  '2375',
  '2376',
  '2378',
  '2379',
  '2384',
  '2385',
  '2388',
  '2389',
  '2391',
  '2393',
  '2395',
  '2397',
  '2404',
  '2408',
  '2410',
  '2411',
  '2413',
  '2415',
  '2418',
  '2425',
  '2428',
  '2429',
  '2432',
  '2433',
  '2435',
  '2436',
  '2437',
  '2438',
  '2440',
  '2445',
  '2449',
  '2454',
  '2459',
  '2461',
  '2462',
  '2464',
  '2467',
  '2468',
  '2469',
  '2471',
  '2475',
  '2477',
  '2479',
  '2480',
  '2481',
  '2483',
  '2484',
  '2485',
  '2487',
  '2488',
  '2491',
  '2492',
  '2493',
  '2497',
  '2498',
  '2499',
  '2501',
  '2502',
  '2503',
  '2531',
  '2533',
  '2540',
  '2551',
  '2573',
  '2579',
  '2585',
  '2586',
  '2588',
  '2590',
  '2593',
  '2594',
  '2597',
  '2599',
  '2602',
  '2607',
  '2612',
  '2613',
  '2651',
  '2652',
  '2653',
  '2654',
  '2656',
  '2659',
  '2664',
  '2666',
  '2667',
  '2668',
  '2669',
  '2670',
  '2673',
  '2674',
  '2676',
  '2678',
  '2681',
  '2683',
  '2685',
  '2686',
  '2687',
  '2689',
  '2692',
  '2693',
  '2694',
  '2695',
  '2698',
  '2700',
  '2702',
  '2705',
  '2708',
  '2715',
  '2721',
  '2722',
  '2726',
  '2730',
  '2733',
  '2734',
  '2735',
  '2736',
  '2737',
  '2742',
  '2743',
  '2749',
  '2750',
  '2751',
  '2752',
  '2753',
  '2754',
  '2760',
  '2762',
  '2763',
  '2764',
  '2767',
  '2768',
  '2769',
  '2776',
  '2778',
  '2780',
  '2782',
  '2784',
  '2788',
  '2789',
  '2790',
  '2791',
  '2792',
  '2795',
  '2796',
  '2798',
  '2801',
  '2802',
  '2804',
  '2805',
  '2806',
  '2809',
  '2810',
  '2811',
  '2813',
  '2814',
  '2815',
  '2816',
  '2818',
  '2819',
  '2830',
  '2831',
  '2871',
  '2872',
  '2874',
  '2875',
  '2876',
  '2877',
  '2882',
  '2883',