In [4]:
import pandas as pd

from utils.datapath import edinet_codes_path, adj_share_counts_path
from utils.datetime import date_to_quarter

In [5]:
pd.set_option('display.max_rows', None)

In [6]:
df = pd.read_excel(edinet_codes_path)
df.info()

FileNotFoundError: [Errno 2] No such file or directory: '../refdata/edinet_codes.xlsx'

In [4]:
df.columns

Index(['EDINET Code', 'Type of Submitter', 'Listed company / Unlisted company',
       'Consolidated / NonConsolidated', 'Capital stock',
       'account closing date', 'Submitter Name', 'Submitter Name（alphabetic）',
       'Submitter Name（phonetic）', 'Province', 'Submitter's industry',
       'Securities Identification Code', 'Submitter's Japan Corporate Number'],
      dtype='object')

In [5]:
# Ensure all SIC ends with 0
columns = {
    "EDINET Code": "edinet_code",
    "Submitter Name（alphabetic）": "company_name",
    "Submitter's industry": "industry",
    "Securities Identification Code": "code",
}

valid_company_df = df[columns.keys()].dropna()

last_0 = valid_company_df["Securities Identification Code"].apply(
    lambda x: str(x)[-1] == "0"
)
valid_company_df[~last_0]

Empty DataFrame
Columns: [EDINET Code, Submitter Name（alphabetic）, Submitter's industry, Securities Identification Code]
Index: []

In [6]:
valid_company_df = valid_company_df.rename(columns = columns)
valid_company_df["code"] = valid_company_df["code"].apply(lambda x: str(x)[0:-1]) # Remove trailing "0"

In [7]:
# valid_company_df.to_dict('records')
# with open(all_securities_path, 'w', encoding='utf-8') as f:
#     json.dump(valid_company_df.to_dict('records'), f)

In [2]:
from utils.data import all_securities

stock_list = [security["code"] for security in all_securities]

In [3]:
import os
import requests
import warnings

from dotenv import load_dotenv
from tqdm import tqdm

warnings.filterwarnings('ignore')

load_dotenv()
JQUANT_API_KEY = os.getenv("JQUANT_API_KEY")

API_URL = "https://api.jquants.com"

In [4]:
refreshtoken = JQUANT_API_KEY

res = requests.post(f"{API_URL}/v1/token/auth_refresh?refreshtoken={refreshtoken}")
if res.status_code == 200:
    id_token = res.json()['idToken']
    headers = {'Authorization': 'Bearer {}'.format(id_token)}
    display("You got an idToken")
else:
    display(res.json()["message"])

'You got an idToken'

In [5]:
def get_average_share_count_adj_series(code, headers):
    params = {}
    params["code"] = code
    res = requests.get(f"{API_URL}/v1/fins/statements", params=params, headers=headers)
    if res.status_code == 200:
        df = pd.DataFrame(res.json()["statements"])
        
        shares_df = df[["CurrentPeriodEndDate", "AverageNumberOfShares"]]
        shares_df["CurrentPeriodEndDate"] = pd.to_datetime(shares_df["CurrentPeriodEndDate"])
        shares_df = shares_df[shares_df["AverageNumberOfShares"].str.isdigit()].sort_values("CurrentPeriodEndDate")
        
        shares_df["Quarter"] = shares_df["CurrentPeriodEndDate"].apply(date_to_quarter)
        shares_df = shares_df.drop_duplicates(subset="Quarter")
        shares_df = shares_df[["Quarter", "AverageNumberOfShares"]]
        
        shares_df["AverageNumberOfShares"] = shares_df["AverageNumberOfShares"].astype(int)
        shares_df["split_factor"] = shares_df["AverageNumberOfShares"].pct_change().round(decimals=3) + 1
        shares_df["split_factor"] = shares_df["split_factor"].shift(-1)
        shares_df["split_factor"] = shares_df["split_factor"].iloc[::-1].cumprod().iloc[::-1].ffill()

        shares_df["AverageNumberOfSharesAdj"] = (shares_df["AverageNumberOfShares"] * shares_df["split_factor"]).astype(int)
        
        return shares_df.set_index("Quarter")["AverageNumberOfSharesAdj"].rename(code)
    else:
        return pd.Series(name=code)

In [8]:
complete_shares_df = pd.DataFrame()
error_codes = []

for code in tqdm(stock_list):
    try:
        series = get_average_share_count_adj_series(code, headers)
        complete_shares_df = pd.concat([complete_shares_df, series.to_frame()], axis=1)
    except:
        print(f"Error for stock code: {code}")
        error_codes.append(code)

# Error for stock code: 187A
# Error for stock code: 9388

  0%|          | 0/3578 [00:00<?, ?it/s]

 11%|█▏        | 410/3578 [03:27<23:40,  2.23it/s]

Error for stock code: 187A

 98%|█████████▊| 3506/3578 [29:35<00:32,  2.19it/s]

Error for stock code: 9388

100%|██████████| 3578/3578 [30:08<00:00,  1.98it/s]

In [ ]:
complete_shares_df = complete_shares_df.sort_index()
# complete_shares_df.to_csv(adj_share_counts_path)

In [13]:
complete_shares_df

,6178,8316,8411,8306,9501,9432,8421,6758,4612,7203,...,4894,9330,5889,151A,135A,143A,9345,3045,5591,3350
Quarter,,,,,,,,,,,,,,,,,,,,,
2014-Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-Q4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-Q2,NaN,3.903605e+09,2.528081e+09,1.164707e+10,1.602365e+09,8.343758e+10,8700240.0,6.052410e+09,2.345976e+09,1.319752e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2146047.0,NaN,4.075926e+08
2015-Q3,3.103619e+09,3.903595e+09,2.529171e+09,1.165004e+10,1.602359e+09,8.344884e+10,8703028.0,6.050962e+09,2.345973e+09,1.319822e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2146717.0,NaN,4.074673e+08
2015-Q4,3.102263e+09,3.903585e+09,2.529108e+09,1.164881e+10,1.602354e+09,8.344720e+10,8703084.0,6.050386e+09,2.345971e+09,1.320082e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2147521.0,NaN,4.074818e+08
2016-Q1,3.100761e+09,3.903578e+09,2.528011e+09,1.164498e+10,1.602347e+09,8.348796e+10,8704061.0,6.052763e+09,2.345970e+09,1.320621e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148330.0,NaN,4.074818e+08
2016-Q2,3.100430e+09,3.903562e+09,2.529005e+09,1.164654e+10,1.602312e+09,8.349687e+10,8704521.0,6.053733e+09,2.345962e+09,1.320697e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2149235.0,NaN,4.074818e+08
2016-Q3,3.100283e+09,3.903557e+09,2.528029e+09,1.164576e+10,1.602308e+09,8.349388e+10,8704521.0,6.054494e+09,2.345960e+09,1.321227e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2149671.0,NaN,NaN
2016-Q4,3.100235e+09,3.903550e+09,2.528457e+09,1.164827e+10,1.602305e+09,8.348918e+10,8704521.0,6.055361e+09,2.345958e+09,1.321672e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,NaN
2017-Q1,3.100211e+09,3.905389e+09,2.528572e+09,1.164431e+10,1.602301e+09,8.345930e+10,8704521.0,6.056134e+09,2.345947e+09,1.321376e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074341e+08
2017-Q2,3.100147e+09,3.904848e+09,2.529105e+09,1.164169e+10,1.602280e+09,8.344143e+10,8704521.0,6.054385e+09,2.345945e+09,1.321265e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074341e+08
2017-Q3,3.099656e+09,3.905462e+09,2.529030e+09,1.164467e+10,1.602276e+09,8.342249e+10,8704521.0,6.055659e+09,2.345943e+09,1.321121e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074341e+08
2017-Q4,3.101100e+09,3.905660e+09,2.529057e+09,1.164371e+10,1.602271e+09,8.345723e+10,8704521.0,6.057092e+09,2.345941e+09,1.320810e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.073564e+08
2018-Q1,3.101937e+09,3.905761e+09,2.529030e+09,1.164661e+10,1.602267e+09,8.346558e+10,8704521.0,6.059059e+09,2.345934e+09,1.320957e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074976e+08
2018-Q2,3.100802e+09,3.906630e+09,2.528876e+09,1.164974e+10,1.602248e+09,8.342867e+10,8704521.0,6.058160e+09,2.345932e+09,1.321020e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074704e+08
2018-Q3,3.100810e+09,3.906932e+09,2.528713e+09,1.165042e+10,1.602244e+09,8.344901e+10,8704521.0,6.060635e+09,2.345932e+09,1.321206e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.075064e+08
2018-Q4,3.100814e+09,3.907118e+09,2.528613e+09,1.165102e+10,1.602241e+09,8.348516e+10,8704521.0,6.062730e+09,2.345951e+09,1.321051e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.074467e+08
2019-Q1,3.100815e+09,3.905255e+09,2.528634e+09,1.165112e+10,1.602238e+09,8.349351e+10,8704521.0,6.059886e+09,2.346012e+09,1.321023e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.072996e+08
2019-Q2,3.100835e+09,3.906443e+09,2.528448e+09,1.164911e+10,1.602225e+09,8.349896e+10,8704521.0,6.061345e+09,2.346048e+09,1.321332e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.072871e+08
2019-Q3,3.100838e+09,3.904912e+09,2.528352e+09,1.165034e+10,1.602225e+09,8.350834e+10,8704521.0,6.062180e+09,2.346100e+09,1.321491e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.071437e+08
2019-Q4,3.100839e+09,3.905989e+09,2.528482e+09,1.165500e+10,1.602223e+09,8.351767e+10,8704521.0,6.060851e+09,2.346160e+09,1.321645e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.073236e+08
2020-Q1,3.100845e+09,3.904570e+09,2.528463e+09,1.164973e+10,1.602220e+09,8.354296e+10,8704521.0,6.062224e+09,2.346483e+09,1.321698e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.073032e+08
2020-Q2,3.100925e+09,3.904432e+09,2.528480e+09,1.164535e+10,1.602208e+09,8.350901e+10,8704521.0,6.061227e+09,2.346560e+09,1.321676e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.073654e+08
2020-Q3,3.100933e+09,3.905710e+09,2.528235e+09,1.164656e+10,1.602207e+09,8.350578e+10,8704521.0,6.060961e+09,2.346644e+09,1.322315e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.072954e+08
2020-Q4,3.100937e+09,3.906065e+09,2.528078e+09,1.164729e+10,1.602204e+09,8.352299e+10,8704521.0,6.060807e+09,2.346730e+09,1.322527e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.071895e+08
2021-Q1,3.100939e+09,3.906270e+09,2.528081e+09,1.164776e+10,1.602202e+09,8.354686e+10,8704521.0,6.061524e+09,2.346656e+09,1.322629e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.070001e+08
2021-Q2,3.100945e+09,3.907047e+09,2.527738e+09,1.164384e+10,1.602188e+09,8.355059e+10,8704521.0,6.061859e+09,2.345939e+09,1.322876e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148808.0,NaN,4.069969e+08
2021-Q3,3.102134e+09,3.907534e+09,2.527514e+09,1.164341e+10,1.602186e+09,8.355398e+10,8704521.0,6.064031e+09,2.346611e+09,1.322789e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148798.0,NaN,4.069949e+08
2021-Q4,3.102405e+09,3.907689e+09,2.527373e+09,1.164586e+10,1.602183e+09,8.358154e+10,8704521.0,6.064199e+09,2.347775e+09,1.323440e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148740.0,NaN,4.069928e+08
2022-Q1,3.101697e+09,3.907763e+09,2.527298e+09,1.164149e+10,1.602180e+09,8.357148e+10,8704521.0,6.062533e+09,2.348247e+09,1.323441e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148740.0,NaN,4.069813e+08
2022-Q2,3.103158e+09,3.908173e+09,2.526617e+09,1.164716e+10,1.602167e+09,8.360133e+10,8704521.0,6.060906e+09,2.348269e+09,1.323247e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148740.0,NaN,4.069768e+08
2022-Q3,3.104603e+09,3.908665e+09,2.526708e+09,1.165030e+10,1.602164e+09,8.362506e+10,8704521.0,6.061558e+09,2.348295e+09,1.323724e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148740.0,NaN,4.069742e+08
2022-Q4,3.104633e+09,3.908034e+09,2.526730e+09,1.165264e+10,1.602161e+09,8.360190e+10,8704521.0,6.059374e+09,2.348322e+09,1.323873e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2148740.0,NaN,4.069715e+08
2023-Q1,3.105194e+09,3.906365e+09,2.526742e+09,1.165294e+10,1.602159e+09,8.362663e+10,8704521.0,6.057043e+09,2.348458e+09,1.324026e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,1605956.0,2148740.0,NaN,4.069838e+08
2023-Q2,3.104428e+09,3.904922e+09,2.526691e+09,1.165414e+10,1.602143e+09,8.362731e+10,8704521.0,6.055949e+09,2.348489e+09,1.324666e+10,...,7999566.0,NaN,NaN,NaN,NaN,NaN,1606100.0,2148740.0,NaN,4.069942e+08
2023-Q3,3.104099e+09,3.906576e+09,2.526981e+09,1.165496e+10,1.602139e+09,8.361788e+10,8704521.0,6.054345e+09,2.348513e+09,1.324375e+10,...,7998470.0,1419746.0,NaN,NaN,NaN,NaN,1605837.0,2148740.0,6103520.0,4.068567e+08
2023-Q4,3.104188e+09,3.905449e+09,2.527059e+09,1.165541e+10,1.602136e+09,8.359176e+10,8704521.0,6.055314e+09,2.348532e+09,1.324232e+10,...,7999077.0,1419463.0,24005361.0,NaN,NaN,NaN,1605461.0,2148740.0,6103896.0,4.068210e+08
2024-Q1,3.105032e+09,3.905151e+09,2.527075e+09,1.165037e+10,1.602131e+09,8.361683e+10,8708376.0,6.053329e+09,2.348637e+09,1.324452e+10,...,7998441.0,1419490.0,24001027.0,8390999.0,10112586.0,1910935.0,1605333.0,2148740.0,6104602.0,4.068484e+08
2024-Q2,3.106588e+09,3.905240e+09,2.526991e+09,1.164531e+10,1.602101e+09,8.357805e+10,8708222.0,6.051388e+09,2.348653e+09,1.324142e+10,...,8001131.0,1419550.0,23992172.0,8389911.0,10110000.0,1911425.0,1604758.0,2148740.0,6105353.0,4.069740e+08
2024-Q3,3.107012e+09,3.905162e+09,2.527160e+09,1.164831e+10,1.602097e+09,8.355676e+10,8708222.0,6.051001e+09,2.348669e+09,1.324219e+10,...,8001389.0,1419685.0,23992172.0,8392362.0,10110000.0,1912240.0,1605526.0,2148740.0,6106262.0,4.084386e+08
2024-Q4,3.105950e+09,3.905474e+09,2.528270e+09,1.164789e+10,1.602094e+09,8.359126e+10,8708222.0,6.051182e+09,2.348682e+09,1.324834e+10,...,8005101.0,1420256.0,23986768.0,8391299.0,10110000.0,1911833.0,1605961.0,2148740.0,6105010.0,4.085936e+08
2025-Q1,3.075134e+09,3.894737e+09,2.523246e+09,1.161886e+10,1.602090e+09,8.336002e+10,8708222.0,6.043602e+09,2.348752e+09,1.318619e+10,...,8018195.0,1421533.0,24022732.0,8430036.0,10110000.0,1913506.0,1619568.0,2148740.0,6150245.0,8.522477e+09
2025-Q2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Create baskets
# Top 1000 stocks by market cap per quarter

# TODO:
# 1. Create function to get historical market cap for single stock
# 3. Get historical shares outstanding - Done (for last 10 years)
# 3. Adjust for stock splits - Done

# 4. Compute market cap by multiplying with prices
# 5. Form quarterly baskets
# 6. Form quarterly baskets with current market cap (to see difference)